CMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from CMS import views

app_name = "CMS"

urlpatterns = [
    #path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('contact/', views.contact, name='contact'),
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/register/", views.register_request, name="register"),



]

if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'blog'

urlpatterns = [

    path('', views.paragraph, name='paragraph'),
    path('blog/', views.blog, name='blog'),
    path('search/', views.search, name='search'),
    path('blogpost/<str:slug>/', views.blogpost, name='blog'),
    path('tags/<str:tag_slug>/', views.posts_by_tag, name='posts_by_tag'),


]
urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

STATUS = (
    (0, "Draft"),
    (1, "Publish"),
    (2, "Delete"),
)


class BlogPost(models.Model):
    sno = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    content = models.TextField()
    cover = models.ImageField(upload_to='images/', null=True, blank=True)
    created_on = models.DateTimeField(auto_now=True, auto_created=True, null=False, blank=False)
    # published_on = models.DateTimeField(null=True)
    # updated_on = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = TaggableManager()

    def __str__(self):
        return self.title

class HomepageParagraph(models.Model):
    sno = models.AutoField(primary_key=True)
    title = models.TextField(blank=True)
    subtitle = models.TextField(blank=True)
    content = models.TextField()
    cover = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return self.title

CMS/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

CMS/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login
from .forms import NewUserForm
from django.contrib import messages



def home(request):
    return render(request, 'index.html')


def contact(request):
    return render(request, 'contact.html')


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.is_staff = True
            user.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("/blog/")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="registration/register.html", context={"register_form": form})

blog/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth import authenticate, login
from taggit.models import Tag

from blog.models import BlogPost
from blog.models import HomepageParagraph
from django.core.paginator import Paginator
from django.db.models import Q


# Create your views here.


def get_posts_page(posts, request):
    tags = Tag.objects.all()
    p = Paginator(posts, 5)
    page = request.GET.get('page')
    pages = p.get_page(page)
    context = {
        'tags': tags,
        'pages': pages,
        'nums': range(pages.paginator.num_pages)
    }
    return context


def blog(request):
    posts = BlogPost.objects.order_by('-created_on').all()
    context = get_posts_page(posts, request)
    return render(request, 'bloghome.html', context)

def paragraph(request):
    paragraphs = HomepageParagraph.objects.all()
    context = {'paragraphs': paragraphs}
    return render(request, 'index.html', context)

def blogpost(request, slug):
    blog = BlogPost.objects.get(slug=slug)
    tags = Tag.objects.all()
    context = {'blog': blog, 'tags': tags}
    return render(request, 'blogpost.html', context)


def search(request):
    search_post = request.GET.get("search")

    if search_post:
        posts = BlogPost.objects.filter(
            Q(title__icontains=search_post) | Q(content__icontains=search_post) | Q(tags__name__icontains=search_post))
    else:
        posts = BlogPost.objects.all()

    posts = posts.order_by('-created_on')
    context = get_posts_page(posts, request)
    context["search"] = search_post
    return render(request, 'bloghome.html', context)


def posts_by_tag(request, tag_slug):
    posts = BlogPost.objects.filter(tags__slug=tag_slug).order_by("-created_on")
    return render(request, 'bloghome.html', get_posts_page(posts, request))

templates/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %}

    {% endblock title %}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <style>
        .img-fluid-resize {
        width: 100%;
        height: auto;
        }
    </style>

    <!-- =======================================================
    * Template Name: Moderna - v4.10.1
    * Template URL: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center ">
    <div class="container d-flex justify-content-between align-items-center">

        <div class="logo">
            <h1 class="text-light"><a href="/"><span>Awesome blog</span></a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <nav id="navbar" class="navbar">
            <ul>
                <li><a class="" href="/">Home</a></li>
                <li><a href="/blog">Blog</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="/accounts/logout">Logout</a></li>
                {% else %}
                    <li><a href="/accounts/login">Login</a></li>
                    <li><a href="/accounts/register">Register</a></li>
                {% endif %}
                <li><a href="/contact">Contact Us</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->
<div class="container d-flex justify-content-between align-items-center">
    <div class="row">
        {% block body %}{% endblock body %}
    </div>
</div>
<!-- ======= Footer ======= -->
<footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">



    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-contact">
                    <h4>Contact Us</h4>
                    <p>
                        A108 Adam Street <br>
                        New York, NY 535022<br>
                        United States <br><br>
                        <strong>Phone:</strong> +1 5589 55488 55<br>
                        <strong>Email:</strong> info@example.com<br>
                    </p>

                </div>

                <div class="col-lg-3 col-md-6 footer-info">
                    <h3>About Moderna</h3>
                    <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita
                        valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
                    <div class="social-links mt-3">
                        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>Moderna</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/bloghome.html
{% extends 'base.html' %}
{% block body %}
    <main id="main">


        <!-- ======= Blog Section ======= -->
        <section id="blog" class="blog">
            <div class="container" data-aos="fade-up">
                <div class="row">
                    <div class="col-lg-8 entries">
                        {% if not pages %}
                            <div class="card text-center">
                            <div class="card-header">

                                </div>
                                    <div class="card-body">
                                    <h5 class="card-title">Oops...</h5>
                                    <p class="card-text">Unfortunately we did not find what you are looking for, please try again.</p>

                                    </div>
                                <div class="card-footer text-muted">

                            </div>
                            </div>

                        {% endif %}


                        {% for blog in pages %}
                            <article class="entry">
                                <div class="entry-img">
                                    <img src="{% if blog.cover %}
                                    {{ blog.cover.url }}
                                    {% else %}
                                    {% load static %}
                                    {% static "blog/Blog_pic.png" %}
                                    {% endif %} " alt="{{ blog.title }}" class="img-fluid-resize">
                                </div>

                                <h2 class="entry-title">
                                    <a href="/blogpost/{{ blog.slug }}">{{ blog.title }}</a>
                                </h2>

                                <div class="entry-meta">
                                    <ul>
                                        <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a
                                                href="#">{{ blog.author }}</a></li>
                                        <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a
                                                href="#">{{ blog.created_on }}</a></li>
                                    </ul>
                                </div>


                                <div class="entry-content">
                                    <p>
                                        {{ blog.content|slice:250 }}...
                                    </p>
                                    <div class="entry-meta">
                                    <i class="bi bi-tag"></i>
                                        {% for tags in blog.tags.all %}
                                            <a href="{% url "blog:posts_by_tag" tag_slug=tags.slug %}"
                                               class="badge text-decoration-none bg-light">
                                                {{ tags }}
                                            </a>
                                        {% endfor %}
                                    </div>
                                    <div class="read-more">
                                        <a href="/blogpost/{{ blog.slug }}">Read More</a>
                                    </div>
                                </div>


                            </article><!-- End blog entry -->
                        {% endfor %}

                        <div class="blog-pagination">
                            <ul class="justify-content-center">
                                {% if pages.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ pages.previous_page_number }}">Previous</a>
                                    </li>
                                {% endif %}

                                {% for i in nums %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                                    </li>
                                {% endfor %}

                                {% if pages.has_next %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ pages.next_page_number }}">Next</a></li>
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ pages.paginator.num_pages }}">Last
                                        &raquo</a></li>
                                {% endif %}
                            </ul>
                        </div>

                    </div><!-- End blog entries list -->

                    <div class="col-lg-4">

                        <div class="sidebar">
                            {% if request.user.is_authenticated %}
                                <h3 class="sidebar-title">User panel</h3>
                                <div class="sidebar-item categories">
                                    You are logged in as <b>{{ request.user }}</b>.
                                    <ul>
                                        <li><a href="/admin">Admin panel</a></li>
                                        <li><a href="/accounts/logout">Logout</a></li>
                                    </ul>
                                </div>
                            {% endif %}
                            <h3 class="sidebar-title">Search</h3>
                            <div class="sidebar-item search-form">
                                <form action="{% url 'blog:search' %}">
                                    {#                                    {% csrf_token %}#}
                                    <input type="text" {% if search %}value="{{ search }}"
                                           {% else %}placeholder="Search"{% endif %} name="search">
                                    <button type="submit"><i class="bi bi-search"></i></button>
                                </form>
                            </div><!-- End sidebar search formn-->


                            <h3 class="sidebar-title">Tags</h3>
                            <div class="sidebar-item tags">
                                <ul>
                                    {% for tag in tags %}
                                        <li><a href="{% url "blog:posts_by_tag" tag_slug=tag.slug %}">{{ tag.name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div><!-- End sidebar tags-->

                        </div><!-- End sidebar -->

                    </div><!-- End blog sidebar -->

                </div>

            </div>
        </section><!-- End Blog Section -->

    </main><!-- End #main -->
{% endblock body %}

templates/blogpost.html
{% extends 'base.html'%}
{% block body %}
<main id="main">

    <!-- ======= Blog Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Blog</h2>

          <ol>
            <li><a href="/">Home</a></li>
            <li><a href="/blog">Blog</a></li>
            <li>{{blog.title}}</li>
          </ol>
        </div>

      </div>
    </section><!-- End Blog Section -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">

            <article class="entry">

              <div class="entry-img">
                <img src="{% if blog.cover %}
                {{blog.cover.url}}
                {% else %}
                {% load static %}
                {% static "blog/Blog_pic.png" %}
                {% endif %} " alt="{{blog.title}}" class="img-fluid-resize">
              </div>

              <h2 class="entry-title">
                <a href="/blogpost/{{blog.slug}}">{{ blog.title }}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="#">{{blog.author}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="#">{{ blog.created_on }}</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  {{ blog.content }}
                </p>
              </div>

                <div>
                    {% for tags in blog.tags.all %}
                        <a href="{% url "blog:posts_by_tag" tag_slug=tags.slug %}"
                           class="badge text-decoration-none bg-secondary">
                            {{ tags }}
                        </a>
                    {% endfor %}
                </div>

            </article><!-- End blog entry -->

          </div><!-- End blog entries list -->

          <div class="col-lg-4">

            <div class="sidebar">
              {% if request.user.is_authenticated %}
              <h3 class="sidebar-title">User panel</h3>
              <div class="sidebar-item categories">
                You are logged in as <b>{{request.user}}</b>.
                <ul>
                  <li><a href="/admin">Admin panel</a></li>
                  <li><a href="/accounts/logout">Logout</a></li>
                </ul>
              </div>
              {% endif %}
              <h3 class="sidebar-title">Search</h3>
              <div class="sidebar-item search-form">
                <form action="">
                  <input type="text">
                  <button type="submit"><i class="bi bi-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->


              <h3 class="sidebar-title">Tags</h3>
              <div class="sidebar-item tags">
                <ul>
                    {% for tag in tags %}
                        <li><a href="{% url "blog:posts_by_tag" tag_slug=tag.slug %}">{{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
              </div><!-- End sidebar tags-->

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->
{% endblock body %}

templates/contact.html
{% extends 'base.html'%}
{% block body %}
this is my contact page
{% endblock body %}

templates/index.html
{% extends 'base.html'%}
{% block body %}
<main id="main">
    {% if request.user.is_authenticated %}
    <h3>Hello, {{request.user}}!</h3>
    {% endif %}
    {% for paragraph in paragraphs %}
    {% if paragraph.title == "" %}
    {% else %}
    <h1>{{ paragraph.title }}</h1>
    {% endif %}
    {% if paragraph.subtitle == "" %}
    {% else %}
    <h3>{{ paragraph.subtitle }}</h3>
    {% endif %}
    <p>
        {{ paragraph.content }}
    </p>
        {% if paragraph.cover %}
        <div class="entry-img">
            <img src="{{ paragraph.cover.url }}" alt="{{ paragraph.title }}" class="img-fluid-resize">
        </div>
        {% endif %}
    {% endfor %}
</main>
{% endblock body %}